version: "3.9"

services:
  api:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - DATABASE_URL=postgresql://neondb_owner:npg_1HgrXSj8mTGC@ep-lingering-recipe-aixyu1zb-pooler.c-4.us-east-1.aws.neon.tech/neondb?sslmode=require
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - GOOGLE_CLOUD_PROJECT=${GOOGLE_CLOUD_PROJECT}
      - GOOGLE_APPLICATION_CREDENTIALS=/app/credentials.json
      - SECRET_KEY=${SECRET_KEY}
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    extra_hosts:
      - "host.docker.internal:host-gateway"